---
- name: Prepare operator metadata for usage with the operator testing pipeline
  hosts: all
  become: false
  gather_facts: false

  vars:
    operator_work_dir: "/home/jenkins/agent/test-operator"
    operator_dir: "/tmp/test"
    work_dir: "{{ lookup('env', 'WORKSPACE') }}"
    jq_bin_path : "/usr/bin/jq"
    yq_bin_path: "/usr/local/bin/yq"
    testing_bin_path: "/usr/local/bin"
    current_channel: '' # Added to avoid a bug with undefined variables

  tasks:
    - name: "Run operator-courier nest to copy the operator metadata in nested format to the work dir"
      shell: "operator-courier nest {{ operator_dir }} {{ operator_work_dir }}"

    - name: "Parse operator metadata needed to run the tests"
      include_role:
        name: parse_operator_metadata
