---
- name: "Create the kube_objects directory"
  file:
    path: "{{ kube_objects_dir }}"
    state: directory
    mode: '0755'

- name: "Read the PGP encoded kube_objects and store them in a file"
  shell: "echo \"{{ kube_objects }}\" > {{ kube_objects_dir }}/get_kubeObjects.txt"

- name: "Decode the kube_objects using the gpg key"
  shell: "gpg --decrypt {{ kube_objects_dir }}/get_kubeObjects.txt > {{ kube_objects_dir }}/kube_objects.yaml"

- name: "Create the kube_objects on the testing openshift cluster for operator certification"
  shell: "oc apply -f {{ kube_objects_dir }}/kube_objects.yaml"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: "Read yaml file content to get the namespace"
  set_fact:
    content="{{ lookup('file', '{{ kube_objects_dir }}/kube_objects.yaml') | from_yaml }}"
  no_log: true
  ignore_errors: true

- name: "Verify kube_objects created on openshift cluster"
  shell: "oc get secrets -n {{ content.metadata.namespace }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ignore_errors: true

- name: "Remove the directory created for kube_object"
  shell: "rm -rf {{ kube_objects_dir }}"
  register: kube_objects_directory_removed

- debug:
    msg: "The kube_objects directory has been removed successfully"
  when: kube_objects_directory_removed.rc == 0
